const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * Expo config plugin: wire a real release signing config into the generated
 * `android/app/build.gradle`.
 *
 * The generated project signs release builds with the *debug* keystore — which is
 * the public, shared key everyone's Android SDK has (`androiddebugkey` / password
 * `android`). That's fine for `expo run:android` on your own device, but it provides
 * zero authenticity for APKs handed to other people: anyone can forge a "signed
 * update". This plugin lets release builds use YOUR private keystore instead.
 *
 * Credentials are read from Gradle properties (never committed). The recommended place
 * is the GLOBAL `~/.gradle/gradle.properties` (outside the repo entirely):
 *
 *   AV_UPLOAD_STORE_FILE=/absolute/path/to/arsivinyo-release.keystore
 *   AV_UPLOAD_STORE_PASSWORD=...
 *   AV_UPLOAD_KEY_ALIAS=arsivinyo
 *   AV_UPLOAD_KEY_PASSWORD=...
 *
 * If those properties are absent (e.g. a contributor without the key, or CI), release
 * builds transparently fall back to debug signing so the build still succeeds — it just
 * produces an APK you wouldn't distribute as an official update.
 *
 * OPTIONAL: sign DEBUG builds with the release key too. Set
 *
 *   AV_SIGN_DEBUG_WITH_RELEASE=true
 *
 * (alongside the AV_UPLOAD_* props) and debug builds will be signed with your release
 * key as well. The point: a debug build (with Metro / fast-refresh) can then be installed
 * as an *update* over an already-installed release build of the same app, because the
 * signatures match — so you don't have to uninstall (which would wipe app-private data
 * like the encrypted vault). Caveat: your debug APKs then carry your production signature,
 * so they're no longer distinguishable from a release build by signature — don't hand them
 * out as throwaway debug builds. Default (flag absent/false): debug uses the debug keystore.
 *
 * Because `android/` is regenerated by prebuild, this is applied as a plugin rather than
 * a hand-edit so it survives `expo prebuild --clean`.
 */

const MARKER = "project.hasProperty('AV_UPLOAD_STORE_FILE')";

const RELEASE_SIGNING_CONFIG_BLOCK = `        release {
            // @generated by plugins/withReleaseSigning.js
            if (${MARKER}) {
                storeFile file(AV_UPLOAD_STORE_FILE)
                storePassword AV_UPLOAD_STORE_PASSWORD
                keyAlias AV_UPLOAD_KEY_ALIAS
                keyPassword AV_UPLOAD_KEY_PASSWORD
            }
        }
`;

// Debug buildType signing: use the release key only when the keystore is configured
// AND the explicit opt-in flag is set; otherwise fall back to the debug keystore.
// NOTE: the entire ternary must be wrapped in parentheses so Groovy treats it as the
// single argument to signingConfig(...). Without the outer parens, `signingConfig (cond)`
// parses as a method call passing the boolean, which then fails to cast to a SigningConfig.
const DEBUG_SIGNING_EXPR =
  "signingConfig((project.hasProperty('AV_UPLOAD_STORE_FILE') && project.findProperty('AV_SIGN_DEBUG_WITH_RELEASE')?.toBoolean()) ? signingConfigs.release : signingConfigs.debug)";

function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error('[withReleaseSigning] Expected a groovy android/app/build.gradle');
    }

    let contents = cfg.modResults.contents;

    // 1) Insert a `release` signingConfig right after the generated `debug` one,
    //    inside the `signingConfigs { ... }` block. Idempotent on the MARKER.
    if (!contents.includes(MARKER)) {
      const debugSigningAnchor =
        /(signingConfigs\s*\{[\s\S]*?debug\s*\{[\s\S]*?keyPassword\s+'android'\s*\n\s*\})/;
      if (!debugSigningAnchor.test(contents)) {
        throw new Error('[withReleaseSigning] Could not find the debug signingConfig anchor in build.gradle');
      }
      contents = contents.replace(debugSigningAnchor, `$1\n${RELEASE_SIGNING_CONFIG_BLOCK}`);
    }

    // 2) Point the release buildType at the release signingConfig when the keystore
    //    properties are present, else keep debug. The comment line above the default
    //    `signingConfig signingConfigs.debug` is unique to the release buildType, so we
    //    anchor on it to avoid touching the debug buildType's identical line.
    const releaseBuildTypeAnchor =
      /(\/\/ see https:\/\/reactnative\.dev\/docs\/signed-apk-android\.\s*\n\s*)signingConfig signingConfigs\.debug/;
    if (releaseBuildTypeAnchor.test(contents)) {
      contents = contents.replace(
        releaseBuildTypeAnchor,
        `$1signingConfig ${MARKER} ? signingConfigs.release : signingConfigs.debug`,
      );
    }

    // 3) Optionally point the DEBUG buildType at the release signingConfig (gated at
    //    Gradle-eval time by AV_SIGN_DEBUG_WITH_RELEASE). The buildTypes `debug {` block
    //    is the only place where `debug {` is immediately followed by
    //    `signingConfig signingConfigs.debug` (the signingConfigs `debug {` is followed
    //    by `storeFile ...`), so this anchor is unambiguous and idempotent.
    const debugBuildTypeAnchor = /(\bdebug\s*\{\s*\n\s*)signingConfig signingConfigs\.debug/;
    if (debugBuildTypeAnchor.test(contents)) {
      contents = contents.replace(debugBuildTypeAnchor, `$1${DEBUG_SIGNING_EXPR}`);
    }

    cfg.modResults.contents = contents;
    return cfg;
  });
}

module.exports = withReleaseSigning;
