const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * Expo config plugin: wire a real release signing config into the generated
 * `android/app/build.gradle`.
 *
 * The generated project signs release builds with the *debug* keystore — which is
 * the public, shared key everyone's Android SDK has (`androiddebugkey` / password
 * `android`). That's fine for `expo run:android` on your own device, but it provides
 * zero authenticity for APKs handed to other people: anyone can forge a "signed
 * update". This plugin lets release builds use YOUR private keystore instead.
 *
 * Credentials are read from Gradle properties (never committed). The recommended place
 * is the GLOBAL `~/.gradle/gradle.properties` (outside the repo entirely):
 *
 *   AV_UPLOAD_STORE_FILE=/absolute/path/to/arsivinyo-release.keystore
 *   AV_UPLOAD_STORE_PASSWORD=...
 *   AV_UPLOAD_KEY_ALIAS=arsivinyo
 *   AV_UPLOAD_KEY_PASSWORD=...
 *
 * If those properties are absent (e.g. a contributor without the key, or CI), release
 * builds transparently fall back to debug signing so the build still succeeds — it just
 * produces an APK you wouldn't distribute as an official update.
 *
 * Because `android/` is regenerated by prebuild, this is applied as a plugin rather than
 * a hand-edit so it survives `expo prebuild --clean`.
 */

const MARKER = "project.hasProperty('AV_UPLOAD_STORE_FILE')";

const RELEASE_SIGNING_CONFIG_BLOCK = `        release {
            // @generated by plugins/withReleaseSigning.js
            if (${MARKER}) {
                storeFile file(AV_UPLOAD_STORE_FILE)
                storePassword AV_UPLOAD_STORE_PASSWORD
                keyAlias AV_UPLOAD_KEY_ALIAS
                keyPassword AV_UPLOAD_KEY_PASSWORD
            }
        }
`;

function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error('[withReleaseSigning] Expected a groovy android/app/build.gradle');
    }

    let contents = cfg.modResults.contents;

    // Idempotent: bail if we've already injected.
    if (contents.includes(MARKER)) {
      return cfg;
    }

    // 1) Insert a `release` signingConfig right after the generated `debug` one,
    //    inside the `signingConfigs { ... }` block.
    const debugSigningAnchor =
      /(signingConfigs\s*\{[\s\S]*?debug\s*\{[\s\S]*?keyPassword\s+'android'\s*\n\s*\})/;
    if (!debugSigningAnchor.test(contents)) {
      throw new Error('[withReleaseSigning] Could not find the debug signingConfig anchor in build.gradle');
    }
    contents = contents.replace(debugSigningAnchor, `$1\n${RELEASE_SIGNING_CONFIG_BLOCK}`);

    // 2) Point the release buildType at the release signingConfig when the keystore
    //    properties are present, else keep debug. The comment line above the default
    //    `signingConfig signingConfigs.debug` is unique to the release buildType, so we
    //    anchor on it to avoid touching the debug buildType's identical line.
    const releaseBuildTypeAnchor =
      /(\/\/ see https:\/\/reactnative\.dev\/docs\/signed-apk-android\.\s*\n\s*)signingConfig signingConfigs\.debug/;
    if (!releaseBuildTypeAnchor.test(contents)) {
      throw new Error('[withReleaseSigning] Could not find the release buildType signingConfig anchor in build.gradle');
    }
    contents = contents.replace(
      releaseBuildTypeAnchor,
      `$1signingConfig ${MARKER} ? signingConfigs.release : signingConfigs.debug`,
    );

    cfg.modResults.contents = contents;
    return cfg;
  });
}

module.exports = withReleaseSigning;
