apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'expo-module-gradle-plugin'

group = 'expo.modules.localdownloader'
version = '1.0.0'

android {
  namespace "expo.modules.localdownloader"
  defaultConfig {
    minSdkVersion rootProject.ext.minSdkVersion
    targetSdkVersion rootProject.ext.targetSdkVersion
  }
}

dependencies {
  implementation 'expo.modules:core'
  implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1"
  implementation "com.chaquo.python:runtime:15.0.1"
}
