# Shrinker rules contributed by the local-downloader module.
#
# These are merged into the app's R8 configuration automatically. They live here because
# android/ is regenerated by `expo prebuild`, so anything written into
# android/app/proguard-rules.pro is lost on the next run.

# --- BouncyCastle (Argon2id for backup key derivation) ---
#
# Only org.bouncycastle.crypto.generators.Argon2BytesGenerator and its parameter classes
# are reachable, so R8 strips the rest of the jar. What it cannot resolve on its own are
# BouncyCastle's references to JCE/JSSE classes that exist on a desktop JVM but not on
# Android. Those code paths are unreachable here; silence the warnings rather than
# dragging the whole provider in.
-dontwarn org.bouncycastle.jce.**
-dontwarn org.bouncycastle.jsse.**
-dontwarn org.bouncycastle.jcajce.**
-dontwarn javax.naming.**
